### PR TITLE
merge upstream changes

### PR DESCRIPTION
**Pull request by monsieurleberre**

### CODE REVIEW

**Comment by joaofbvieira** [comment]
@monsieurleberre should we still keep this repo and this PR?

**Comment by monsieurleberre** [comment]
OK I removed the conflicts, so we can merge, but I think that we cannot get rid of it just yet, as the package is in use in the current user-verification solution

**Comment by monsieurleberre** [comment]
I will now press the button, codacy is not being helpful.

**Comment by monsieurleberre** [comment]
@joaofbvieira you are correct I think that we can get rid of this entirely as the `user-verification` repo is using a nuget from nuget.org => the original repo

**Pull request merged**
